source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SVEJSONObject_Example', :exclusive => true do
  pod 'SVEJSONObject', :path => '../'
end

target 'SVEJSONObject_Tests', :exclusive => true do
  pod 'SVEJSONObject', :path => '../'

  
end
