osx_image: xcode7.3
language: objective-c
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/SVEJSONObject.xcworkspace -scheme SVEJSONObject-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
